version: "3.7"
services:
  splynx:
    build:
      context: .
      dockerfile: Dockerfile
    image: pliuta/splynx
    container_name: splynx-container
    ports: 
      - "80:80"
      - "443:443"
      - "1812:1812/udp"
      - "1813:1813/udp"
    tmpfs:
      - /var/tmp
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - splynx-files:/var/www/splynx
      - splynx-mysql-data:/var/lib/mysql
      - splynx-etc:/etc
      - splynx-logs:/var/log
    privileged: true
#
volumes:
  splynx-files:
  splynx-mysql-data:
  splynx-etc:
  splynx-logs:
